//Script Version: 3.1
(function(){function q(g){function v(a){k("PANEL_EXPANDED",{panelName:a.eventData.props.panel.name})}function w(a){k("PANEL_COLLAPSED",{panelName:a.eventData.props.panel.name})}function x(a,c){if(g&&g.panels){var f=c?EBG.adaptor.getElementById(e.panels[c].divId):EBG.adaptor.getElementById(EBG.Const.OUTER_DIV);f&&(f.style.zIndex=a)}}function y(){var a="";if(g&&g.panels)for(var c in g.panels){var f=g.panels[c];f.CC.isExpanded()&&(a+=f.name+"$")}""!=a&&(a=a.substring(0,a.length-1));return a}function z(a){if(g&&
g.panels){var c=a.panelName?g.panels[a.panelName]:s;if(c){var f={};void 0!=a.x&&(c.CC.props.panel.left=a.x,c.CC.props.expand.left=a.x,f.left=a.x);void 0!=a.y&&(c.CC.props.panel.top=a.y,c.CC.props.expand.top=a.y,f.top=a.y);void 0!=a.width&&(c.CC.props.panel.width=a.width,c.CC.props.expand.width=a.width,f.width=a.width);void 0!=a.height&&(c.CC.props.panel.height=a.height,c.CC.props.expand.height=a.height,f.height=a.height);c.CC.modifyPanel(f);c=EBG.adaptor.getElementById(c.CC._flashResID);a.width&&
(c.style.width=a.width+"px");a.height&&(c.style.height=a.height+"px")}}}function A(a){if(""!=a&&0<h.mdAutoRepositionInterval){var c=a.split("$");B.setInterval(function(){try{for(var a=0;a<c.length;a++){var b=e.panels[c[a]];b&&b.CC._panelVisible&&b.CC.recalculatePanelPosition()}}catch(d){}},h.mdAutoRepositionInterval)}}function C(a){D&&EBG.adaptor.browser.isSafari()&&(a.style.opacity=".99",setTimeout(function(){a.style.opacity="1"},1))}function E(a){try{console&&console.log(a)}catch(c){}}function t(a){setTimeout(function(){k("PAGE_LOADED")},
100)}function F(a,c,f){b.subscriptions[c]={};b.subscriptions[c].eventType=a;b.subscriptions[c].interAd=f}function G(a){for(var c in b.subscriptions)if(c==a){b.subscriptions[c]=void 0;break}}function k(a,c){for(var f in b.subscriptions){var d=b.subscriptions[f],e=f.match(r),g=EBG.adaptor.getElementById(f.split("||")[1]);c=c||{};c.type=a;c.source={adId:u,rnd:r};if(d&&d.eventType==a&&(e||d.interAd)&&g[f])try{g[f](c)}catch(h){}}}function H(){b.registeredAssets={}}function I(a,c){function f(){b.registeredAssets.count>
a||(b.registeredAssets.assetFail=!0,clearTimeout(b.registeredAssets.timeoutAssetFail),k(e.mdAssetsReadyEvent,{isLoaded:!1}))}b.registeredAssets=b.registeredAssets||{};b.registeredAssets.count=b.registeredAssets.count||1;if(void 0==b.registeredAssets.assetFail)b.registeredAssets.assetFail=!1;else if(b.registeredAssets.assetFail){k(e.mdAssetsReadyEvent,{isLoaded:!1});return}void 0==b.registeredAssets.timeoutAssetFail&&(b.registeredAssets.timeoutAssetFail=setTimeout(f,parseInt(1E3*c)));b.registeredAssets.count!=
a||b.registeredAssets.assetFail||k(e.mdAssetsReadyEvent,{isLoaded:!0});b.registeredAssets.count++}function J(a,c,f,b,e){e=e||d._defaultPanel;e=EBG.adaptor.getElementById(d._panels[e.toLowerCase()].divId);EBG.adaptor.clip(e,c,a+f,c+b,a);C(e)}function K(a){a=a||d._defaultPanel;a=EBG.adaptor.getElementById(d._panels[a.toLowerCase()].divId);EBG.adaptor.unclip(a)}function l(a,c){var b=h.hasOwnProperty(a)?h[a]:c;"true"==b&&(b=!0);"false"==b&&(b=!1);"undefined"==b&&(b=void 0);h[a]=b;h.customJSVars[a]=b}
var m=new EBG.Events.EventSubscription(EBG.Events.EventNames.SHOW_AD,function(a){if(a.dispatcher._adConfig.uid==n){e.customJSVars=e.customJSVars||{};try{d.panelFrequencyMgr.init(e.frequencyTimes,e.frequencyPeriod,e.adId,e.histLen,EBG.adaptor.optOut,e.disableAutoExpand),l("mdShouldAutoExpand",1<e.uponShow&&d.panelFrequencyMgr.shouldExpand())}catch(c){}l("mdCustomJSPath","EBG.ads['"+n+"'].public.");l("mdAssetsReadyEvent","assetsReadyEvent");l("mdEyeDivZIndex",void 0);l("mdAutoRepositionInterval",0);
l("mdAutoRepositionPanels","");A(h.mdAutoRepositionPanels)}});m.timing=EBG.Events.EventTiming.BEFORE;EBG.eventMgr.subscribeToEvent(m);d=this;h=e=g;p=EBG.adaptor.getDisplayWin();p.gEbPIT=p.gEbPIT||{};var D=EBG.adaptor.browser.isMac()||0<navigator.platform.indexOf("Mac");b=p.gEbPIT;b.subscriptions=b.subscriptions||{};EBG.callSuperConstructor(q,d,[e]);if(d._canShow()&&1!=e.showOnlyImage){try{d._subscribeToAdEvent(EBG.Events.EventNames.EXPAND,v,EBG.Events.EventTiming.AFTER),d._subscribeToAdEvent(EBG.Events.EventNames.COLLAPSE,
w,EBG.Events.EventTiming.AFTER)}catch(L){}d["public"]={};d["public"].addJSEventListener=F;d["public"].removeJSEventListener=G;d["public"].dispatchJSEvent=k;d["public"].changeZIndex=x;d["public"].registerAsset=I;d["public"].clipAsset=J;d["public"].unclipAsset=K;d["public"].modifyPanelDimension=z;d["public"].getListOfExpandedPanels=y;d["public"].resetRegisterAsset=H;d["public"].log=E;try{s=d._panels[d._defaultPanel.toLowerCase()],l("mdDefaultPanelName",d._defaultPanel.toLowerCase())}catch(M){}EBG.adaptor.isPageLoaded()?
t():(m=new EBG.Events.EventSubscription(EBG.Events.EventNames.PAGE_LOAD,t),m.timing=EBG.Events.EventTiming.BEFORE,EBG.eventMgr.subscribeToEvent(m))}else EBG.adaptor.getElementById("ebDefaultImg_"+n)}var u=window.ebAdID||0,r=ebRand,n=u+"_"+r,B=this,d=void 0,e=void 0,b=void 0,p=void 0,h=void 0,s=void 0;ebO.extensionHooks.push(function(){var b=new EBG.Events.EventSubscription(EBG.Events.EventNames.CREATE_AD,function(b){b.eventData.adConfig.uid==n&&(EBG.declareClass(q,b.eventData.currentClass),b.eventData.currentClass=
q)});b.timing=EBG.Events.EventTiming.BEFORE;EBG.eventMgr.subscribeToEvent(b)})})();